/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schedules/{scheduleId}/attendance-check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reissueAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schedules/{scheduleId}/attendance-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentCode"];
        put?: never;
        post: operations["createOrReissueCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 업로드 완료 검증 및 파일 자산 등록 */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/file-upload-urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 파일 업로드 URL 발급 */
        post: operations["createUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/admin/resources/{resourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/admin/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_2"];
        trace?: never;
    };
    "/api/admin/notices/{noticeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_3"];
        trace?: never;
    };
    "/api/admin/attendances/{attendanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAttendance"];
        trace?: never;
    };
    "/api/admin/accounts/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch: operations["update_4"];
        trace?: never;
    };
    "/api/admin/accounts/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeRole"];
        trace?: never;
    };
    "/api/admin/accounts/{userId}/rejection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["reject"];
        trace?: never;
    };
    "/api/admin/accounts/{userId}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["approve"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSchedules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{resourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{resourceId}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notices/{noticeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cohorts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 기수 목록 조회 (번호 내림차순) */
        get: operations["getCohorts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{certificateId}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDownloadUrl_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["previewMyCertificateData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/kakao/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["loginRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/kakao/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attendances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/attendances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAttendances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AttendanceCheckInRequest: {
            code?: string;
        };
        AttendanceResponse: {
            /** Format: int64 */
            attendanceId?: number;
            /** Format: int64 */
            userId?: number;
            userName?: string;
            /** @enum {string} */
            part?: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
            /** Format: int64 */
            scheduleId?: number;
            scheduleTitle?: string;
            /** Format: date */
            scheduleDate?: string;
            /** @enum {string} */
            status?: "NOT_CHECKED" | "PRESENT" | "LATE" | "ABSENT";
            /** Format: date-time */
            checkedAt?: string;
            /** @enum {string} */
            checkInSource?: "SELF_CODE" | "ADMIN";
            memo?: string;
            /** Format: int32 */
            version?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CertificatePreviewResponse: {
            name?: string;
            department?: string;
            studentId?: string;
            cohort?: components["schemas"]["CohortSummary"];
            /** @enum {string} */
            part?: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
            /** Format: date */
            activityStartedAt?: string;
            /** Format: date */
            activityEndedAt?: string;
        };
        CertificateResponse: {
            /** Format: int64 */
            certificateId?: number;
            /** @enum {string} */
            status?: "ISSUED" | "FAILED";
            snapshot?: components["schemas"]["CertificatePreviewResponse"];
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CohortSummary: {
            /** Format: int64 */
            cohortId?: number;
            /** Format: int32 */
            number?: number;
            name?: string;
        };
        AccessTokenResponse: {
            accessToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresIn?: number;
            account?: components["schemas"]["AccountResponse"];
        };
        AccountResponse: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            department?: string;
            studentId?: string;
            cohort?: components["schemas"]["CohortSummary"];
            /** @enum {string} */
            part?: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
            /** @enum {string} */
            role?: "MEMBER" | "ADMIN";
            /** @enum {string} */
            status?: "PENDING" | "ACTIVE" | "REJECTED";
            rejectionReason?: string;
            /** Format: int32 */
            version?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateScheduleRequest: {
            title?: string;
            description?: string;
            /** Format: int64 */
            cohortId: number;
            /** Format: date */
            scheduleDate: string;
            isAllDay: boolean;
            /** @example 14:30:00 */
            startTime?: string;
            location?: string;
        };
        ScheduleResponse: {
            /** Format: int64 */
            scheduleId?: number;
            title?: string;
            description?: string;
            cohort?: components["schemas"]["CohortSummary"];
            /** Format: date */
            scheduleDate?: string;
            isAllDay?: boolean;
            /** @example 14:30:00 */
            startTime?: string;
            location?: string;
            /** Format: int32 */
            version?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AttendanceCodeResponse: {
            /** Format: int64 */
            scheduleId?: number;
            code?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        CreateLearningResourceRequest: {
            title?: string;
            /** Format: int32 */
            week: number;
            /** @enum {string} */
            targetPart: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
            /** Format: int64 */
            fileAssetId: number;
        };
        FileAssetResponse: {
            /** Format: int64 */
            fileAssetId?: number;
            /** @enum {string} */
            purpose?: "PROJECT_THUMBNAIL" | "LEARNING_RESOURCE" | "NOTICE_IMAGE" | "CERTIFICATE";
            originalFileName?: string;
            mimeType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        LearningResourceResponse: {
            /** Format: int64 */
            resourceId?: number;
            title?: string;
            /** Format: int32 */
            week?: number;
            /** @enum {string} */
            targetPart?: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
            /** Format: int64 */
            createdBy?: number;
            file?: components["schemas"]["FileAssetResponse"];
            /** Format: int32 */
            version?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateProjectRequest: {
            title?: string;
            description?: string;
            /** @enum {string} */
            projectType: "HACKATHON" | "IDEATHON";
            /** Format: int64 */
            thumbnailAssetId?: number;
            deployUrl?: string;
            githubUrl?: string;
            /** Format: int64 */
            cohortId: number;
            /** Format: date */
            startedMonth: string;
            /** Format: date */
            endedMonth: string;
            dateRangeValid?: boolean;
            deployUrlValid?: boolean;
            githubUrlValid?: boolean;
        };
        AdminProjectResponse: {
            /** Format: int64 */
            projectId?: number;
            title?: string;
            description?: string;
            /** @enum {string} */
            projectType?: "HACKATHON" | "IDEATHON";
            /** Format: int64 */
            thumbnailAssetId?: number;
            deployUrl?: string;
            githubUrl?: string;
            cohort?: components["schemas"]["CohortSummary"];
            /** @example 2025-03 */
            startedMonth?: string;
            /** @example 2025-03 */
            endedMonth?: string;
            /** Format: int64 */
            createdBy?: number;
            /** Format: int32 */
            version?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateNoticeRequest: {
            title?: string;
            content?: string;
            /** @enum {string} */
            tag: "SCHEDULE" | "PROJECT" | "PROMOTION_EVENT" | "OTHER";
            isFixed?: boolean;
            externalUrl?: string;
            /** Format: int64 */
            imageAssetId?: number;
            externalUrlValid?: boolean;
        };
        NoticeResponse: {
            /** Format: int64 */
            noticeId?: number;
            title?: string;
            content?: string;
            /** @enum {string} */
            tag?: "SCHEDULE" | "PROJECT" | "PROMOTION_EVENT" | "OTHER";
            isFixed?: boolean;
            externalUrl?: string;
            /** Format: int64 */
            createdBy?: number;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: int32 */
            version?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        FileAssetRequest: {
            /** @enum {string} */
            purpose: "PROJECT_THUMBNAIL" | "LEARNING_RESOURCE" | "NOTICE_IMAGE" | "CERTIFICATE";
            objectKey?: string;
            originalFileName?: string;
            mimeType?: string;
            /** Format: int64 */
            sizeBytes: number;
            checksumSha256?: string;
        };
        FileUploadUrlRequest: {
            /** @enum {string} */
            purpose: "PROJECT_THUMBNAIL" | "LEARNING_RESOURCE" | "NOTICE_IMAGE" | "CERTIFICATE";
            originalFileName?: string;
            mimeType?: string;
            /** Format: int64 */
            sizeBytes: number;
            checksumSha256?: string;
        };
        FileUploadUrlResponse: {
            uploadUrl?: string;
            objectKey?: string;
            requiredHeaders?: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt?: string;
        };
        CreateAccountRequest: {
            name?: string;
            department?: string;
            studentId?: string;
            /** Format: int64 */
            cohortId: number;
            /** @enum {string} */
            part: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
        };
        UpdateScheduleRequest: {
            /** Format: int32 */
            version: number;
            title?: string;
            description?: string;
            /** Format: date */
            scheduleDate?: string;
            isAllDay?: boolean;
            /** @example 14:30:00 */
            startTime?: string;
            location?: string;
            allDayProvided?: boolean;
            anyChangeProvided?: boolean;
            providedValueValid?: boolean;
        };
        UpdateLearningResourceRequest: {
            /** Format: int32 */
            version: number;
            title?: string;
            /** Format: int32 */
            week?: number;
            /** @enum {string} */
            targetPart?: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
            /** Format: int64 */
            fileAssetId?: number;
            anyChangeProvided?: boolean;
            providedValueValid?: boolean;
        };
        UpdateProjectRequest: {
            /** Format: int32 */
            version: number;
            title?: string;
            description?: string;
            /** @enum {string} */
            projectType?: "HACKATHON" | "IDEATHON";
            /** Format: int64 */
            thumbnailAssetId?: number;
            deployUrl?: string;
            githubUrl?: string;
            /** Format: int64 */
            cohortId?: number;
            /** Format: date */
            startedMonth?: string;
            /** Format: date */
            endedMonth?: string;
            anyChangeProvided?: boolean;
            providedValueValid?: boolean;
            deployUrlValid?: boolean;
            githubUrlValid?: boolean;
        };
        UpdateNoticeRequest: {
            /** Format: int32 */
            version: number;
            title?: string;
            content?: string;
            /** @enum {string} */
            tag?: "SCHEDULE" | "PROJECT" | "PROMOTION_EVENT" | "OTHER";
            isFixed?: boolean;
            externalUrl?: string;
            /** Format: int64 */
            imageAssetId?: number;
            fixedProvided?: boolean;
            anyChangeProvided?: boolean;
            providedValueValid?: boolean;
            externalUrlValid?: boolean;
        };
        UpdateAttendanceRequest: {
            /** @enum {string} */
            status: "PRESENT" | "LATE" | "ABSENT";
            memo?: string;
            /** Format: int32 */
            version: number;
            memoValid?: boolean;
        };
        UpdateAccountRequest: {
            /** Format: int32 */
            version: number;
            name?: string;
            department?: string;
            studentId?: string;
            /** @enum {string} */
            part?: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
            /** Format: int64 */
            cohortId?: number;
            anyChangeProvided?: boolean;
            providedValueValid?: boolean;
        };
        UpdateRoleRequest: {
            /** @enum {string} */
            role: "MEMBER" | "ADMIN";
            /** Format: int32 */
            version: number;
        };
        RejectAccountRequest: {
            rejectionReason?: string;
            /** Format: int32 */
            version: number;
        };
        ApproveAccountRequest: {
            /** Format: int32 */
            version: number;
        };
        PageMeta: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
        };
        PageResponseLearningResourceResponse: {
            items?: components["schemas"]["LearningResourceResponse"][];
            page?: components["schemas"]["PageMeta"];
        };
        DownloadUrlResponse: {
            downloadUrl?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        FileView: {
            file?: components["schemas"]["FileAssetResponse"];
            downloadUrl?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        PageResponseProjectResponse: {
            items?: components["schemas"]["ProjectResponse"][];
            page?: components["schemas"]["PageMeta"];
        };
        ProjectParticipantResponse: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            role?: string;
        };
        ProjectResponse: {
            /** Format: int64 */
            projectId?: number;
            title?: string;
            description?: string;
            deployUrl?: string;
            githubUrl?: string;
            /** @example 2025-03 */
            startedMonth?: string;
            /** @example 2025-03 */
            endedMonth?: string;
            /** Format: int32 */
            version?: number;
            /** @enum {string} */
            projectType?: "HACKATHON" | "IDEATHON";
            thumbnail?: components["schemas"]["FileView"];
            cohort?: components["schemas"]["CohortSummary"];
            participants?: components["schemas"]["ProjectParticipantResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PageResponseNoticeResponse: {
            items?: components["schemas"]["NoticeResponse"][];
            page?: components["schemas"]["PageMeta"];
        };
        LionResponse: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            cohort?: components["schemas"]["CohortSummary"];
            /** @enum {string} */
            part?: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
            activityType?: string;
        };
        PageResponseLionResponse: {
            items?: components["schemas"]["LionResponse"][];
            page?: components["schemas"]["PageMeta"];
        };
        PageResponseAttendanceResponse: {
            items?: components["schemas"]["AttendanceResponse"][];
            page?: components["schemas"]["PageMeta"];
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageResponseAccountResponse: {
            items?: components["schemas"]["AccountResponse"][];
            page?: components["schemas"]["PageMeta"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceCheckInRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttendanceResponse"];
                };
            };
        };
    };
    issueCertificate: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CertificateResponse"];
                };
            };
        };
    };
    reissueAccessToken: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: {
                refresh_session?: string;
                csrf_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccessTokenResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScheduleResponse"];
                };
            };
        };
    };
    getCurrentCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttendanceCodeResponse"];
                };
            };
        };
    };
    createOrReissueCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttendanceCodeResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLearningResourceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningResourceResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProjectResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoticeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NoticeResponse"];
                };
            };
        };
    };
    completeUpload: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileAssetRequest"];
            };
        };
        responses: {
            /** @description 파일 자산 등록 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileAssetResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileAssetResponse"];
                };
            };
            /** @description 관리자 권한 필요 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileAssetResponse"];
                };
            };
            /** @description 발급 기록 또는 S3 객체 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileAssetResponse"];
                };
            };
            /** @description 멱등 키 또는 파일 자산 충돌 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileAssetResponse"];
                };
            };
            /** @description 파일 크기 제한 초과 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileAssetResponse"];
                };
            };
            /** @description 지원하지 않는 파일 형식 */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileAssetResponse"];
                };
            };
            /** @description 업로드 메타데이터 불일치 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileAssetResponse"];
                };
            };
            /** @description S3 연동 실패 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileAssetResponse"];
                };
            };
        };
    };
    createUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileUploadUrlRequest"];
            };
        };
        responses: {
            /** @description Presigned PUT URL 발급 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileUploadUrlResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileUploadUrlResponse"];
                };
            };
            /** @description 관리자 권한 필요 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileUploadUrlResponse"];
                };
            };
            /** @description 파일 크기 제한 초과 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileUploadUrlResponse"];
                };
            };
            /** @description 지원하지 않는 파일 형식 */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileUploadUrlResponse"];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: {
                onboarding_session?: string;
                csrf_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScheduleResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLearningResourceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningResourceResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProjectResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noticeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoticeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NoticeResponse"];
                };
            };
        };
    };
    updateAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attendanceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAttendanceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttendanceResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getSchedules: {
        parameters: {
            query: {
                yearMonth: string;
                cohortId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScheduleResponse"][];
                };
            };
        };
    };
    getSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScheduleResponse"];
                };
            };
        };
    };
    getResources: {
        parameters: {
            query?: {
                week?: number;
                targetPart?: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseLearningResourceResponse"];
                };
            };
        };
    };
    getResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningResourceResponse"];
                };
            };
        };
    };
    getDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DownloadUrlResponse"];
                };
            };
        };
    };
    getProjects: {
        parameters: {
            query?: {
                cohortId?: number;
                projectType?: ("HACKATHON" | "IDEATHON")[];
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseProjectResponse"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                tag?: "SCHEDULE" | "PROJECT" | "PROMOTION_EVENT" | "OTHER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseNoticeResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noticeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NoticeResponse"];
                };
            };
        };
    };
    getLions: {
        parameters: {
            query?: {
                cohortId?: number;
                part?: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
                role?: "MEMBER" | "ADMIN";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseLionResponse"];
                };
            };
        };
    };
    getCohorts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CohortSummary"][];
                };
            };
        };
    };
    getDownloadUrl_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificateId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DownloadUrlResponse"];
                };
            };
        };
    };
    previewMyCertificateData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CertificatePreviewResponse"];
                };
            };
        };
    };
    loginRedirect: {
        parameters: {
            query?: {
                origin?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    callback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMine: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAttendanceResponse"];
                };
            };
        };
    };
    listAttendances: {
        parameters: {
            query: {
                scheduleId: number;
                part?: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
                userId?: number;
                status?: "NOT_CHECKED" | "PRESENT" | "LATE" | "ABSENT";
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAttendanceResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query: {
                status?: "PENDING" | "ACTIVE" | "REJECTED";
                role?: "MEMBER" | "ADMIN";
                cohortId?: number;
                part?: "PLANNING" | "DESIGN" | "FRONTEND" | "BACKEND" | "COMMON";
                keyword?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAccountResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: {
                refresh_session?: string;
                csrf_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
